<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowMissingPrunePackageData>true</AllowMissingPrunePackageData>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    <PackageReference Include="NSwag.AspNetCore" Version="14.6.0" />
  </ItemGroup>

  <Target Name="gents" AfterTargets="Build" Condition=" '$(Configuration)' == 'Debug' And '$(RunNSwag)' != 'False' And Exists('nswag.json') ">
    <Message Text="--- installing local tools using: dotnet tool restore ---" Importance="high" />
    <Exec WorkingDirectory="$(ProjectDir)" Command="dotnet tool restore" />
    <Message Text="--- generating NSwag typescript API client ---" Importance="high" />
    <Exec WorkingDirectory="$(ProjectDir)" EnvironmentVariables="ASPNETCORE_ENVIRONMENT=Development" Command="dotnet nswag run nswag.json /variables:Configuration=$(Configuration)" />
  </Target>


</Project>
